development: &default
  adapter: postgresql
  database: thirteen23_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000

test:
  <<: *default
  database: thirteen23_test

production:
  <<: *default
  database: thirteen23_production
